services:
  api:
    container_name: projeto-integrador
    image: 'projeto-integrador'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/projeto_integrador_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - MQTT_BROKER_URL=tcp://host.docker.internal:1883
      - MQTT_TOPIC=cerveja/dados
    ports:
      - "8080:8080"

  postgres:
    container_name: postgresql
    image: 'postgres:16-alpine'
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: