spring:
  application:
    name: projeto-integrador

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projeto_integrador_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver

mqtt:
  broker:
    url: ${MQTT_BROKER_URL:tcp://localhost:1883}
  topic: ${MQTT_TOPIC:cerveja/temp_liq}